"""Added nullable false constraints

Revision ID: 880464cc0fc0
Revises: 0e1993d47f54
Create Date: 2026-08-28 19:49:06.789301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880464cc0fc0'
down_revision: Union[str, Sequence[str], None] = '0e1993d47f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('appointments', 'time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('appointments', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
